# Locally override default configurations
#
# This file overrides configurations set in `config/config.defaults.yml`.
# Keep in mind that environment variables override setting in this file.
#
# Usage:
#
# Copy this file from `config/config.example.yml` to `config/config.yml`
#

development:
  # Add local `development` environment configuration overrides here
  domain: "0.0.0.0:3000"
  external_plan_service_in_use: true
  max_image_filesize: 10000000

test:
  # Add local `test` environment configuration overrides here

staging:
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>

production:
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>
